### ISSUE TITLE
Unit tests don't run properly

### ISSUE THREAD

**Issue by kellieotto** [statlab/permute#14]
I seem to be having issues running the tests that I write for the IRR simulation functions.  Specifically, the output of the simulate_ts_dist and simulate_npc_dist functions don't match what is expected when I call "make test" at the command line.

We should figure out a work-around or fix whatever bug is causing this.  It'd be nice not to have to skip tests because they always throw an error!

**Comment by jarrodmillman** [comment]
See:
- 67a8b50fe5ffeb39d37093493dc02c124f12cc94
- d52bd6c1446fc75e870b39761979bdb9d568911c
- 880f85f0302280489b54070366db90e9e2abf001
- 906661c3647ea9fb48ea3fa227728425ee7d9fd2
- 7fcd67e68b065e4e874172723474b1fffcf431ec

Mainly, this:

"""
Create your own instance of numpy.random.RandomState() with your chosen seed. Do not use numpy.random.seed() except to work around inflexible libraries that do not let you pass around your own RandomState instance.
"""

See Robert Kern's answer here:
http://stackoverflow.com/questions/5836335/consistenly-create-same-random-numpy-array
