### ISSUE TITLE
Wrong implementation in "two_sample_shift" when shift != 0. 

### ISSUE THREAD

**Issue by UdiBhaskar** [statlab/permute#154]
Implementation looks like 

```
pot_outx = np.concatenate([x, y + shift])
# Potential outcomes for all units under control
pot_outy = np.concatenate([x - shift, y])
pot_out_all = np.column_stack([pot_outx, pot_outy])

dist[i] = tst_stat(pot_out_all [:nx, 0], pot_out_all [nx:, 1])
```
based on the above code,  `pot_out_all [:nx, 0]` will give the `x` and `pot_out_all [nx:, 1]` will give the `y`. so we are checking `x` and `y` not `x` and `y + shift` or `x-shift` and `y`

**Comment by pbstark** [comment]
Thank you for looking hard at the code!

I believe the implementation is correct. 

The first 4 lines you quote construct the set of potential outcomes in two_sample_shift(). The hypothesis is that y is x, shifted. 

The 5th line you cite is called in two_sample_core() **after the rows of the potential outcomes have been permuted**. If a row that was originally an x ends up still in x, its value is the same. If it ends up in y, the value taken is its original value, minus the shift. Conversely, if a row that was originally a y ends up in y, it's not changed; if it ends up in x, the shift is added to it.
