### ISSUE TITLE
Incorrect spearman correlation calculation (computation of rank)

### ISSUE THREAD

**Issue by kauttoj** [statlab/permute#191]
I think your computation of spearman correlation is wrong. In your "spearman_corr" function you have:

```
xnew = np.argsort(x)+1
ynew = np.argsort(y)+1
```

However, argsort does not give your the actual rank of corresponding elements, just new indexing for sorting (these things are not equal). You should replace those lines, e.g., with scipy.stats.rankdata

```
xnew = rankdata(x, method='average')
ynew = rankdata(y, method='average')
```

This also handles possible tied ranks.

**Comment by pbstark** [comment]
Thank you! 

We should have called argsort() twice: 
    xnew = np.argsort(np.argsort(x))+1
    ynew = np.argsort(np.argsort(y))+1
which does compute the ranks. However, I like your suggestion to use sp.stats.rankdata() because it gives a clean way to use midranks or unique ranks with ties broken arbitrarily. Will merge the fix asap.
