### ISSUE TITLE
IRR p-values when doing NPC

### ISSUE THREAD

**Issue by kellieotto** [statlab/permute#64]
In some small examples, the p-values are behaving in ways we don't understand.

Should we do pre-processing to check if every rater gave a 0?  What should the p-value/test statistic be in that case?

Look starting at line 262 in irr.py, starting with " if pvalues is None: "

**Comment by pbstark** [comment]
If at least n-1 of the n raters each give the same rating at every timestamp (the rating can be different for different raters), the p-value should be 1 for that video: every columnwise permutation of the data will give the same value of the test statistic.

I think.

**Comment by kellieotto** [comment]
Closed by #66
