### ISSUE TITLE
Hypergeometric confidence interval - lower limit too low?

### ISSUE THREAD

**Issue by kellieotto** [statlab/permute#81]
I made up a toy example for writing tests and calculated what I think the confidence intervals should be.  Every time I run the function, the lower limit of the confidence interval it gives me back is one less than the value I expected.  I think it's coming from this chunk:

    if alternative != "upper" and x > 0:
        f = lambda q: cl - hypergeom.cdf(x-1, N, q, n)
        ci_low = (brentq(f, 0.0, G, *kwargs))

because of the x-1 in the call to hypergeom.cdf.  Why do we decrease the number of "good" things by 1 here?  I realize the confidence intervals we get out of this will tend to be conservative so it's not necessarily bad, but I wonder if it's the "correct" thing to do.

**Comment by kellieotto** [comment]
Whoops, I removed the ``math.floor`` here because I wanted to see what the actual values the bisection gave back were.  The last line should be 

`` ci_low = math.floor(brentq(f, 0.0, G, *kwargs))``

**Comment by pbstark** [comment]
Fixed, I think.  The x-1 belonged in the upper interval, not the lower. Added a test to test.py.

**Comment by kellieotto** [comment]
I think this fix is correct.  Two more things now:
1) Looks like maybe the same error appears in binom_conf_interval?
2) The pull request with the fix didn't pass the Travis CI tests.  I found bugs in the code, and an additional bug that only happens when the sample is made entirely of "good" things (n=x).  I will fix these, make your changes, and put in a pull request tonight.

**Comment by pbstark** [comment]
Thank you!

**Comment by kellieotto** [comment]
Closed by #84
