### ISSUE TITLE
add generic test function to two core.two_sample

### ISSUE THREAD

**Issue by pbstark** [statlab/permute#83]
I think in lieu of
   tst_fun = stats[stat]

we can substitute

    if callable(stat):
        tst_fun = stat
    else:
        test_fun = stats[stat]

Thoughts?

**Comment by kellieotto** [comment]
Next steps: 
- Write documentation for two_sample. The code is now implemented.
- Give another test, slightly more complicated. e.g. differences in the maxes of the two sets

**Comment by kellieotto** [comment]
Closed by #85
